# Generated by Django 3.1.3 on 2020-12-02 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Мужской', 'М'), ('Женский', 'Ж')], max_length=60)),
                ('age', models.IntegerField()),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('офтальмолог', 'офтальмолог'), ('лор', 'лор'), ('зубной', 'зубной'), ('терапевт', 'терапевт'), ('педиатр', 'педиатр'), ('кардиолог', 'кардиолог'), ('невролог', 'невролог'), ('хирург', 'хирург'), ('педиатр', 'педиатр')], default='врач', max_length=100)),
                ('rating', models.IntegerField()),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.hospitaluser')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.TimeField(default=django.utils.timezone.now)),
                ('client_appeal', models.CharField(choices=[('Заболел и пришел в первый раз', 'Заболел'), ('На повторный прием', 'Прием'), ('На выписку', 'Выписка')], default='Заболел', max_length=60)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.hospitaluser')),
                ('doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.doctor')),
            ],
        ),
    ]
