# Generated by Django 3.1.4 on 2020-12-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201202_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profession',
            field=models.CharField(choices=[('Офтальмолог', 'Офтальмолог'), ('Хирург', 'Хирург'), ('Психиатр', 'Психиатр'), ('Оттолоринголог', 'Оттолоринголог'), ('Стоматолог', 'Стоматолог'), ('Невролог', 'Невролог'), ('Педиатр', 'Педиатр'), ('Кардиолог', 'Кардиолог')], default='врач', max_length=100),
        ),
    ]
