# Generated by Django 3.1.3 on 2020-12-08 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20201203_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_time',
            new_name='appointment_end',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_start',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
