# Generated by Django 3.1.3 on 2020-12-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20201208_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='room',
            field=models.CharField(default='301', max_length=20),
        ),
    ]
